spring.application.name=dispense

# Dispense server
dispense.server=${DISPENSE_SERVER:merlo:11021}

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URI:https://keycloak.ucc.asn.au/realms/master}

# API docs
springdoc.api-docs.path=/docs/openapi
springdoc.swagger-ui.path=/docs/swagger.html